name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Checker
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v1
    - name: Add remotes for Conan
      run: |
        conan remote add conan https://api.bintray.com/conan/conan/conan-center
        conan remote add epitech https://bintray.com/epitech/public-conan
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        conan profile update settings.compiler.libcxx=libstdc++11 default
      continue-on-error: true
        
    - name: Conan install
      run: rm -rf build && mkdir build && cd build && conan install .. --build=missing

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake .. -G "Unix Makefiles" && cmake --build .

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
